[workspace]

members = [
    "ordering-server",
    "c-ordering-client",
    "protocol-test",
    "streaming-transpositions",
    "viz264",
    "trace-ord",
]

[profile.dev]
# panic = 'abort'
incremental = false

[profile.release]
# panic = 'abort'
incremental = false
