[workspace]

members = [
    "ordering-server",
    "c-ordering-client",
    "protocol-test",
    "streaming-transpositions",
    "viz",
    "trace-ord",
    "lf-trace-reader",
]

resolver = "2"

[profile.dev]
# panic = 'abort'
incremental = false

[profile.release]
incremental = false
